# Generated by Django 4.1.3 on 2022-11-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('FM', 'Family medicine'), ('SR', 'Surgery'), ('AN', 'Anesthesiology')], default='FM', max_length=2),
        ),
    ]
