# Generated by Django 4.1.3 on 2022-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0002_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Family', 'Family'), ('medicine', 'Medicine'), ('Surgery', 'Surgery'), ('Anesthesiology', 'Anesthesiology')], default='FAMILYMEDICINE', max_length=64),
        ),
    ]
