# Generated by Django 4.1.3 on 2022-11-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0003_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('FamilyMedicine', 'Familymedicine'), ('Surgery', 'Surgery'), ('Anesthesiology', 'Anesthesiology'), ('Physiotherapy', 'Physiotherapy'), ('Dental', 'Dental')], default='FAMILYMEDICINE', max_length=256),
        ),
    ]
