# Generated by Django 4.1.3 on 2022-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicApp', '0004_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='imgs/default.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
