# Generated by Django 4.1.3 on 2022-11-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('experience_years', models.IntegerField(default='SOME Integer', verbose_name=100)),
                ('specialization', models.CharField(choices=[('surgery', 'Surgery'), ('familyMedicine', 'Familymedicine'), ('dental', 'Dental'), ('Audiology', 'Audiology'), ('Orthopedics & Rheumatology', 'Orthopedics & Rheumatology'), ('Physiotherapy', 'Physiotherapy'), ('Cardiac ', 'Cardiac ')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=2048)),
                ('case_description', models.TextField()),
                ('patient_age', models.IntegerField(verbose_name=4)),
                ('appointment_datetime', models.DateTimeField()),
                ('is_attended', models.BooleanField()),
                ('relation', models.ManyToManyField(to='clinic.doctor')),
            ],
        ),
    ]
