# Generated by Django 4.1.3 on 2022-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('specialization', models.CharField(max_length=256)),
                ('experience_years', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
