# Generated by Django 4.1.3 on 2022-11-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
