# Generated by Django 4.1.3 on 2022-11-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('specialization', models.CharField(choices=[('famlie', 'Famlie'), ('surgery', 'Surgery'), ('farmci', 'Farmci')], max_length=64)),
                ('experience_years', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=256)),
                ('Patient_Age', models.IntegerField()),
                ('Relation_With_Doctor', models.CharField(max_length=256)),
                ('Case_Description', models.TextField()),
                ('Appointment_Datetime', models.DateTimeField()),
                ('Is_Attended', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicApp.doctor')),
            ],
        ),
    ]
