# Generated by Django 4.1.3 on 2022-11-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Dentistry", "Dentistry"),
                            ("Pediatrice", "Pediatrice"),
                            ("Dermatology", "Dermatology"),
                            ("General Practitoner", "General Practitoner"),
                        ],
                        default=0,
                        max_length=250,
                    ),
                ),
                ("experience_years", models.IntegerField()),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("case_description", models.TextField()),
                ("patient_age", models.IntegerField()),
                ("appointment_datetime", models.DateField()),
                ("is_attended", models.BooleanField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Clinic_app.doctor",
                    ),
                ),
            ],
        ),
    ]
