# Generated by Django 4.1.3 on 2022-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic_app', '0002_alter_appointment_appointment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(),
        ),
    ]
