# Generated by Django 4.1.3 on 2022-11-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Docname', models.CharField(max_length=256)),
                ('DocDescrip', models.TextField()),
                ('DocRate', models.FloatField()),
                ('experience_years', models.IntegerField()),
                ('DocSpecialization', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=256)),
                ('case_description', models.TextField()),
                ('p_age', models.IntegerField()),
                ('Appointment_datetime', models.DateTimeField(auto_now=True)),
                ('is_attend', models.BooleanField()),
                ('Relation_with_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteApp.doctor')),
            ],
        ),
    ]
