# Generated by Django 4.1.3 on 2022-11-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('specialization', models.CharField(max_length=64)),
                ('experience_years', models.CharField(max_length=64)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_with_doctor', models.CharField(max_length=256)),
                ('pationt_name', models.CharField(max_length=64)),
                ('case_description', models.TextField()),
                ('patient_age', models.CharField(max_length=64)),
                ('appointment_datetime', models.DateTimeField()),
                ('is_attended', models.BooleanField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
        ),
    ]
