# Generated by Django 4.1.3 on 2022-11-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_appointment_relation_with_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_age',
            field=models.DateTimeField(),
        ),
    ]
