# Generated by Django 4.1.3 on 2022-11-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_appointment_patient_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment',
            new_name='doctor',
        ),
    ]
