# Generated by Django 4.1.3 on 2022-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('O', 'orthodontics'), ('F', 'fillings'), ('Or', 'oral medicine')], default='O', max_length=256),
        ),
    ]
